'''
	Title: password generator
	author: Priyanshu patel
	copywrite: july, 2020
'''
# this is the program to generate the secure password for your any type of accounts
# this generated passwords will be the combination of special symbols, numbers, uppervcase letters, lower case letters
# and you can see the history of passwords generated by you with the dates
import string
import random
import datetime


print(" you want to see the history of passwords : press = hist")
print(" you want to generate the passwords : press = gen")
mode = str(input(" enter the command : "))

if mode == "gen":
	run = True
	set1 = string.digits
	set2 = string.ascii_lowercase
	set3 = string.ascii_uppercase
	set4 = string.punctuation
	# print(set1, set2, set3, set4)

	# step 1: deciding the length of the password
	# there is an exception handling because here you must enter length of thr string 8 or >8
	print(" length must be more than 8 characters")
	try:
		passLen = int(input(" Enter the length for your password \n"))
	except:
		# if length of the pass is entered incorrectly then this exception will be thrown
		print("enter length properly")
		run = False  # the while loop will not run and program will stop

	while run == True:
		# opens the file which have your passwords list generated by date
		f = open("passHistory.txt", "a") # opens the history file
		x = datetime.datetime.now()  # takes the currunt time
		date = str(x) 
		if passLen >= 8:
			# if the passLen is 8 or more than 8 then -->
			str = [] # empty string
			# all the sets of the characters and numbers are concatinated in str string
			str.extend(list(set1))
			str.extend(list(set2))
			str.extend(list(set3))
			str.extend(list(set4))

			# the string str will have all the characters in sequance
			# so this random.shuffle will shuffle all the elements in the str
			random.shuffle(str)
			print(" your generated password : ")
			print("".join(str[0:passLen]))

			# for the password history
			# write password and date of when it is generated to file
			f.write(" you have generated :")
			f.write("\n")
			f.write(" Date&Time : ")
			f.write(date)
			f.write("\n")
			f.write(" password : ")
			f.write("".join(str[0:passLen]))
			f.write("\n \n")
			f.close()

			run = False
		else:
			print("------- run program again and enter length properly -------")

elif mode == "hist":
	print("* you can olny read this file * \n")
	f = open("passHistory.txt", "r")
	print(f.read(), "\n")

else:
	print(" * enter details or command properly * ")



